### ISSUE TITLE
The fly mount will start to behave like a normal mount

### ISSUE THREAD

**Issue by Gelaytbc** [wowmw/bugtracker#280]
Hello,

I've been noticing this for a while now and it keeps happening:

You fly in Outland with a feeling of happiness (xD) and suddenly boom, you fall to the ground and it ends with death :) If you fall from a smaller height and survive - you find that your fly mount is not able to take off and only jumps like a normal horse :)

I don't think it's possible to take a screenshot, only a video - but I don't really want to do that. Feel free to ask other players as well.

I believe you can handle it. Thanks!

Gelay/MoonwellTBC

**Comment by Gensen1** [comment]
Hello. It is happening in certain location?

**Comment by Gelaytbc** [comment]
Hey, it's happening all over Outland. It happened to me 3 times today. When this happens and I fall, it helps if I start the normal mount and then the fly mount again. But it happens all the time and certainly not only to me :)

**Comment by Gelaytbc** [comment]
Maybe it would be nice if I record it, if you could advise me on a software that is not very HW demanding. But I would probably have to shoot it for too long before that would happen xD

**Comment by Gelaytbc** [comment]
Btw - I use a gryphon from Shadowmoon Valley, I have no experience with any other fly mount.

**Comment by Hentaika** [comment]
Такое бывает, когда стражники из города противоположной фракции подстреливают

**Comment by Gelaytbc** [comment]
Нет, они не стреляли в охранников. Бывает и в зоне, где нет "охранников" лол ^^

**Comment by Hentaika** [comment]
> Нет, они не стреляли в охранников. Бывает и в зоне, где нет "охранников" лол ^^

Скорее всего ты врезался в какую либо текстуру, после этого тоже бывает

**Comment by Gelaytbc** [comment]
I don't know who you are or why you speak Russian. I'm not going to use the translator again for you. I went through enough servers, this didn't happen anywhere ... So don't be stupid and try to help or keep quiet :)

**Comment by Gelaytbc** [comment]
I put in the effort... So I came across the texture :D At first it was some guards shooting :D Bro, are you fazed or what?
Because you are talking nonsense

**Comment by Gelaytbc** [comment]
In the end, I'll find out that it's all my fault :D Actually, every player on moonwell has himself to blame for it :D Please, really shut up, I want to talk about it with competent people, TY.

**Comment by Hentaika** [comment]
Bro, don't be so aggressive. I'm just listing the reasons for the bug that I've encountered myself. Specifying the reasons, why this happened, will help in fixing.

**Comment by Gelaytbc** [comment]
I'm not aggressive, you just wrote 2 absolutely stupid things, especially with the guards who shoot. (???)
I don't deny the texture bug, but it happens everywhere, even outside textures. This community that is on this server is already annoying me and you didn't owe it anything with that comment. Sorry.

**Comment by xPaynex** [comment]
I would like to add more to this issue / Bug.
While in outland on flying mount, it always happens with a little lag spike kind of thing. We are flying on our mount and a brief lag spike will occur then our character (still on mount) will behave like it's on ground mount. Therefore, Character will fall down (still on mount) and die. This happens very consistently even on my 87ms connection.

How to reproduce (in outland):
In outland, get on your flying mount, start flying, after a brief spike lag (or we can say a very brief game freeze) the mount will start behaving like ground mount (lose the ability to fly). If you are far away from ground, you will fall and die. But if you survive, you can't fly again (your fly mount will simply jump when you press the Jump key). You can fly again when you dismount and mount your flying mount again.

What happens when we are not in Outland?:
The lag spike I mentioned above, is not just specific to flying mounts and / or outland. Even in Azeroth, when we are running with or without mount (let's say we have our character on auto run). The same lag spike will happen and our character will "Stop" running. It will stand still unless we make it run again.

I am not sure what is causing this issue. Maybe it's a rollback internet connection thing. But it is definitely server side. When there is small lag spike, the server tries to roll back our performance and on that spot, this bug happens.

**Comment by Gelaytbc** [comment]
Perfect Payne, Ty <3

**Comment by Gensen1** [comment]
> I would like to add more to this issue / Bug. While in outland on flying mount, it always happens with a little lag spike kind of thing. We are flying on our mount and a brief lag spike will occur then our character (still on mount) will behave like it's on ground mount. Therefore, Character will fall down (still on mount) and die. This happens very consistently even on my 87ms connection.
> 
> How to reproduce (in outland): In outland, get on your flying mount, start flying, after a brief spike lag (or we can say a very brief game freeze) the mount will start behaving like ground mount (lose the ability to fly). If you are far away from ground, you will fall and die. But if you survive, you can't fly again (your fly mount will simply jump when you press the Jump key). You can fly again when you dismount and mount your flying mount again.
> 
> What happens when we are not in Outland?: The lag spike I mentioned above, is not just specific to flying mounts and / or outland. Even in Azeroth, when we are running with or without mount (let's say we have our character on auto run). The same lag spike will happen and our character will "Stop" running. It will stand still unless we make it run again.
> 
> I am not sure what is causing this issue. Maybe it's a rollback internet connection thing. But it is definitely server side. When there is small lag spike, the server tries to roll back our performance and on that spot, this bug happens.

Thanks.
